# Generated by Django 5.2.5 on 2025-08-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_course_notecomment_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notecomment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='notecomment',
            name='likes',
        ),
    ]
