# Generated by Django 5.2.5 on 2025-08-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='due_time',
        ),
    ]
