# Generated by Django 5.2.5 on 2025-08-14 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_attachment_assignment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 21, 12, 33, 37, 397092, tzinfo=datetime.timezone.utc)),
        ),
    ]
