# Generated by Django 5.2.5 on 2025-08-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='role_visible_to',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='admin', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
