# Generated by Django 5.2.5 on 2025-08-11 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_rename_message_announcement_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='role_visible_to',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(default='No content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AdminAnnouncement',
        ),
    ]
