# Generated by Django 5.2.5 on 2025-08-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_role_visible_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(default='No content provided'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='role_visible_to',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('all', 'All Roles')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
