# Generated by Django 5.2.5 on 2025-08-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_remove_announcement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='role_visible_to',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
    ]
