# Generated by Django 5.2.5 on 2025-08-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_announcement_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
