# Generated by Django 5.2.5 on 2025-08-12 05:43

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_remove_announcement_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='role_visible_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('all', 'All')], max_length=50),
        ),
    ]
